theme: jekyll-theme-slate
title: CoreMedia CKEditor 5 Plugins
author: CoreMedia
description: >- # Ignore newlines until next element
  CoreMedia's CKEditor 5 Plugins provides plugins for CKEditor 5 with focus
  on integration into CoreMedia CMS.
social-network-links:
  twitter: CoreMedia
show_downloads: true
