packages:
  - packages/*
  - itest
  - app
onlyBuiltDependencies:
  - esbuild
patchedDependencies:
  "@bbob/preset-html5": patches/@bbob__preset-html5.patch
catalog:
  '@babel/core': ^7.25.4
  '@babel/cli': ^7.25.4
  '@babel/plugin-transform-runtime': ^7.25.4
  '@babel/preset-env': ^7.25.4
  '@babel/preset-typescript': ^7.25.4
  '@bbob/core': 4.3.1
  '@bbob/html': 4.3.1
  '@bbob/parser': 4.3.1
  '@bbob/plugin-helper': 4.3.1
  '@bbob/preset': 4.3.1
  '@bbob/preset-html5': 4.3.1
  '@bbob/types': 4.3.1
  '@ckeditor/ckeditor5-dev-translations': ^45.0.8
  '@ckeditor/ckeditor5-dev-utils': ^45.0.8
  '@ckeditor/ckeditor5-inspector': ^4.1.0
  '@ckeditor/ckeditor5-theme-lark': 45.2.1
  '@coremedia-internal/ckeditor5-babel-config': ^1.0.0
  '@coremedia-internal/ckeditor5-coremedia-example-data': ^1.0.0
  '@coremedia-internal/studio-client.test-runner-helper': 0.2.3-alpha.050b44a
  '@coremedia/ckeditor5-bbcode': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-blocklist': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-content-clipboard': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-differencing': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-images': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-link': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-richtext': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-studio-essentials': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-studio-integration': 26.0.1-rc.0
  '@coremedia/ckeditor5-coremedia-studio-integration-mock': 26.0.1-rc.0
  '@coremedia/ckeditor5-data-facade': 26.0.1-rc.0
  '@coremedia/ckeditor5-dataprocessor-support': 26.0.1-rc.0
  '@coremedia/ckeditor5-dialog-visibility': 26.0.1-rc.0
  '@coremedia/ckeditor5-dom-converter': 26.0.1-rc.0
  '@coremedia/ckeditor5-font-mapper': 26.0.1-rc.0
  '@coremedia/ckeditor5-link-common': 26.0.1-rc.0
  '@coremedia/service-agent': ^2.1.2
  '@coremedia/set-version': 1.1.1
  '@eslint/compat': ^1.3.2
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.33.0
  '@jest/globals': ^29.7.0
  '@stylistic/eslint-plugin': ^5.2.3
  '@types/express': ^4.17.21
  '@types/jest': ^29.5.12
  '@types/node': ^22.18.10
  '@types/webpack': ^5.28.5
  '@typescript-eslint/eslint-plugin': ^8.39.1
  '@typescript-eslint/parser': ^8.39.1
  babel-jest: ^29.7.0
  babel-loader: ^8.3.0
  circular-dependency-plugin: ^5.2.2
  ckeditor5: 46.1.1
  copyfiles: ^2.4.1
  css-loader: ^7.1.2
  dotenv: ^16.4.7
  enhanced-resolve: ^5.16.0
  esbuild-loader: ^3.2.0
  eslint: ^9.33.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsdoc: ^54.0.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-tsdoc: ^0.4.0
  expect: ^30.2.0
  expect-playwright: ^0.8.0
  express: ^5.1.0
  get-port: ^7.1.0
  global-jsdom: ^27.0.0
  http-server: ^14.1.1
  jest: ^29.7.0
  jest-circus: ^29.7.0
  jest-config: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  jest-environment-node: ^29.7.0
  jest-playwright-preset: 4.0.0
  jest-runner: ^29.7.0
  jest-transform-stub: ^2.0.0
  jsdom: ^27.0.0
  minimist: ^1.2.8
  node-esapi: ^0.0.1
  package-directory: ^8.1.0
  playwright: ^1.45.1
  playwright-core: ^1.45.1
  postcss: ^8.4.39
  postcss-loader: ^8.1.1
  prettier: ^3.6.2
  raw-loader: ^4.0.2
  rimraf: ^6.0.1
  rxjs: ^7.8.1
  semver: ^7.6.2
  source-map-loader: ^1.0.0
  style-loader: ^4.0.0
  terser-webpack-plugin: ^5.3.10
  ts-jest: ^29.1.2
  ts-node: ^10.9.2
  tslib: ^2.6.3
  tsx: ^4.20.6
  typedoc: ^0.28.14
  typescript: ^5.9.3
  validate-peer-dependencies: ^2.2.0
  wait-for-expect: ^3.0.2
  webpack: ^5.101.3
  webpack-cli: ^6.0.1
  xml-formatter: ^3.6.2
