packages:
  - packages/*
  - tests/*
  - app
allowBuilds:
  esbuild: true
  unrs-resolver: true
catalog:
  '@bbob/core': 4.3.1
  '@bbob/html': 4.3.1
  '@bbob/parser': 4.3.1
  '@bbob/plugin-helper': 4.3.1
  '@bbob/preset': 4.3.1
  '@bbob/preset-html5': 4.3.1
  '@bbob/types': 4.3.1
  '@ckeditor/ckeditor5-dev-translations': ^55.6.1
  '@ckeditor/ckeditor5-dev-utils': ^55.6.1
  '@ckeditor/ckeditor5-inspector': ^5.0.0
  '@ckeditor/ckeditor5-theme-lark': 47.6.2
  '@coremedia-internal/studio-client.test-runner-helper': ^1.1.0
  '@coremedia/service-agent': ^2.1.2
  '@coremedia/set-version': 1.2.1
  '@coremedia/studio-client.build-config': ^1.1.0
  '@coremedia/studio-client.eslint-config': ^1.0.1
  '@eslint/compat': ^1.3.2
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.33.0
  '@playwright/test': ^1.59.1
  '@stylistic/eslint-plugin': ^5.2.3
  '@types/eslint': ^9.6.1
  '@types/node': ^24.12.4
  '@types/webpack': ^5.28.5
  '@typescript-eslint/eslint-plugin': ^8.39.1
  '@typescript-eslint/parser': ^8.39.1
  ci-info: ^3.9.0
  circular-dependency-plugin: ^5.2.2
  ckeditor5: 48.1.1
  copyfiles: ^2.4.1
  css-loader: ^7.1.2
  dotenv: ^16.4.7
  esbuild-loader: ^4.4.3
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsdoc: ^54.0.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-tsdoc: ^0.5.2
  expect: ^30.2.0
  express: ^5.1.0
  global-jsdom: ^27.0.0
  http-server: ^14.1.1
  jsdom: ^27.0.0
  minimist: ^1.2.8
  node-esapi: ^0.0.1
  package-directory: ^8.1.0
  playwright-core: ^1.60.0
  postcss: ^8.5.10
  postcss-loader: ^8.1.1
  prettier: ^3.6.2
  rimraf: ^6.0.1
  rxjs: ^7.8.1
  semver: ^7.6.2
  source-map-loader: ^5.0.0
  style-loader: ^4.0.0
  terser-webpack-plugin: ^5.3.10
  ts-node: ^10.9.2
  tsx: ^4.20.6
  typedoc: ^0.28.14
  typescript: ^5.9.3
  validate-peer-dependencies: ^2.2.0
  webpack: ^5.104.1
  webpack-cli: ^6.0.1
  xml-formatter: ^3.6.2
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@coremedia/*'
  - '@coremedia-internal/*'
  - '@jangaroo/*'
onlyBuiltDependencies:
  - esbuild
patchedDependencies:
  '@bbob/preset-html5': patches/@bbob__preset-html5.patch
