blank_issues_enabled: false
contact_links:
  - name: "\U0001F6A8 Security Issue"
    url: https://www.coremedia.com/support/
    about: |
      Please report security vulnerabilities here.
  - name: "\U0001F9E9 CoreMedia Studio Integration"
    url: https://www.coremedia.com/support/
    about: |
      For issues with respect to CoreMedia Studio Integration please |
      contact our support team.
