/* eslint @typescript-eslint/naming-convention: off */

/**
 * Example Blob Fixture for 10×10 Red PNG.
 */
export const PNG_RED_10x10 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAQMAAAC3/F3+AAAAA1BMVEX/AAAZ4gk3AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQIHWPACwAAHgAB95hMXAAAAABJRU5ErkJggg==";
/**
 * Example Blob Fixture for 240×135 Red PNG.
 */
export const PNG_RED_240x135 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAACHCAIAAACnEEO8AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAACB0RVh0VGl0bGUAUmVkIEltYWdlIEZpeHR1cmUgMjQww5cxMzV/6oVFAAABEklEQVR42u3SAQkAAAgEMbV/5zeGIFuE4zoFf4wEGBoMDYYGQ2NoMDQYGgwNhsbQYGgwNBgaDI2hwdBgaDA0GBpDg6HB0GBoMDSGBkODocHQYGgMDYYGQ4OhwdAYGgwNhgZDY2gwNBgaDA2GxtBgaDA0GBoMjaHB0GBoMDQYGkODocHQYGgwNIYGQ4OhwdBgaAwNhgZDg6HB0BgaDA2GBkODoTE0GBoMDYbG0GBoMDQYGgyNocHQYGgwNBgaQ4OhwdBgaDA0hgZDg6HB0GBoDA2GBkODocHQGBoMDYYGQ4OhMTQYGgwNhsbQYGgwNBgaDI2hwdBgaDA0GBpDg6HB0GBoMDSGBkODocHQYGgMDYaGMwvY/gIN7U7I3gAAAABJRU5ErkJggg==";
/**
 * Example Blob Fixture for 10×10 Green PNG.
 */
export const PNG_GREEN_10x10 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAQMAAAC3/F3+AAAAA1BMVEUA/wA0XsCoAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQIHWPACwAAHgAB95hMXAAAAABJRU5ErkJggg==";
/**
 * Example Blob Fixture for 240×135 Green PNG.
 */
export const PNG_GREEN_240x135 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAACHCAIAAACnEEO8AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAACJ0RVh0VGl0bGUAR3JlZW4gSW1hZ2UgRml4dHVyZSAyNDDDlzEzNeoCT9oAAAESSURBVHja7dIBCQAACASx1/6dNYYgW4TjKhN4oyXA0GBoMDQYGkODocHQYGgwNIYGQ4OhwdBgaAwNhgZDg6HB0BgaDA2GBkODoTE0GBoMDYYGQ2NoMDQYGgwNhsbQYGgwNBgaQ4OhwdBgaDA0hgZDg6HB0GBoDA2GBkODocHQGBoMDYYGQ4OhMTQYGgwNhgZDY2gwNBgaDA2GxtBgaDA0GBoMjaHB0GBoMDSGBkODocHQYGgMDYYGQ4OhwdAYGgwNhgZDg6ExNBgaDA2GBkNjaDA0GBoMDYbG0GBoMDQYGgyNocHQYGgwNIYGQ4OhwdBgaAwNhgZDg6HB0BgaDA2GBkODoTE0GBoMDYYGQ2NoMDScWdf/Ag1zS0U/AAAAAElFTkSuQmCC";
/**
 * Example Blob Fixture for 10×10 Blue PNG.
 */
export const PNG_BLUE_10x10 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAQMAAAC3/F3+AAAAA1BMVEUAAP+KeNJXAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQIHWPACwAAHgAB95hMXAAAAABJRU5ErkJggg==";
/**
 * Example Blob Fixture for 240×135 Blue PNG.
 */
export const PNG_BLUE_240x135 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAACHCAIAAACnEEO8AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAACF0RVh0VGl0bGUAQmx1ZSBJbWFnZSBGaXh0dXJlIDI0MMOXMTM1kw6skwAAARNJREFUeNrt0gEJAAAIBLHX/p01hiBbhOMqmcAXLQGGBkODocHQGBoMDYYGQ4OhMTQYGgwNhgZDY2gwNBgaDA2GxtBgaDA0GBoMjaHB0GBoMDQYGkODocHQYGgwNIYGQ4OhwdAYGgwNhgZDg6ExNBgaDA2GBkNjaDA0GBoMDYbG0GBoMDQYGgyNocHQYGgwNBgaQ4OhwdBgaDA0hgZDg6HB0GBoDA2GBkODoTE0GBoMDYYGQ2NoMDQYGgwNhsbQYGgwNBgaDI2hwdBgaDA0GBpDg6HB0GBoMDSGBkODocHQYGgMDYYGQ4OhMTQYGgwNhgZDY2gwNBgaDA2GxtBgaDA0GBoMjaHB0GBoMDQYGkODoeHMAtcAAg2/P7w5AAAAAElFTkSuQmCC";
/**
 * Example Blob Fixture for 10×10 Gray PNG.
 */
export const PNG_GRAY_10x10 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKBAMAAAB/HNKOAAAAMFBMVEXIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMgyCeFrAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAC0lEQVQIHWOgAAAAADwAAZFvo9AAAAAASUVORK5CYII=";
/**
 * Example Blob Fixture for unreadable state as 24×24 lock-symbol PNG.
 */
export const PNG_LOCK_24x24 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAB90RVh0VGl0bGUATG9jayBJbWFnZSBGaXh0dXJlIDI0w5cyND+RntEAAAFYSURBVEiJ7ZUxq4JQGIYfL2kRBUK0tDZY0C9pcmlMpCIa+ymtTUKr0OCU/6ExCIuoxYZAcLMMvHe6LabhJYcLvdPhnPO+D+f7PjjCer3+Jkd95RkOUHh1IQxDlsslq9WKw+EAQLPZpNvtoqoqkiSl+oW0El0uF6bTKbvdDlmW6XQ6AGw2G3zfR1EUZrMZ9Xo9O+B+v6PrOvv9nslkQr/fRxTFx9lisWA+n6MoCoZhUCg8L0ZiDyzLwnEcxuMxg8HgEQ4giiLD4ZDRaMR2u8WyrMQXJAJs26ZaraJpWqJZ13UqlQq2bWcHnE4n2u12ahMlSaLVanE8HrMDgiCgVColGn9VLpcJgiA74F3KHRAb0zAM6fV6nM9nisUitVotNcDzPG63G41GA9M0Yz2LDW8URbiuC8D1en2sX8l1XaIoiu3//x58AB9ADgBBEP4c9syb+mW+Q7mX6AcWeH9EMzKhnwAAAABJRU5ErkJggg==";
/**
 * Example Blob Fixture for empty state as 24×24 symbol PNG.
 */
export const PNG_EMPTY_24x24 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAACB0RVh0VGl0bGUARW1wdHkgSW1hZ2UgRml4dHVyZSAyNMOXMjRSzyF5AAABjklEQVRIidWUsYrCQBRFz0osJIiViKCIFv5AwEZSpLRMo1jkEyyENGKjtWBj5Q+k9QOsRCSIWitioSgWgoKmd7dYtFkTE0mKvdUMb949M+/NzNd8Pv8mQIWCNAcQ7AKXywXTNJlOp+x2O06nE+fzmWg0Si6XQ1EUVFUlEok4Ar7sStTtdjEMwzE5nU7T6/VIpVLeT/CQJEkUi0UymQyCIHA8HhkMBqzXa/b7PfV6HcMwCIfD3k4wHo9JJBLk8/k/sfv9TrPZZDgcAtDpdFAU5SXAtsmyLL80BwiFQqiq+pyvVis7m89vUTwed7XuY8Bms3mOs9msvwDLsuj3+wDEYjFkWfYPcL1e0XWd7XYLgK7riKLoD8A0TarVKovFAkEQaDQalEolx5y37wDgdrvRbrcZjUYAJJNJWq0WkiS9zXUFOBwOT/NyuUytVnv7RTzkuQeVSsW1+UcAr3JVIlEUKRQKAJ52Dw5/kV8KvESuALPZDE3T0DSNyWTiCeCqB5ZlsVwugd+X7EWBl+j/N/kHBzKDUUt0TnMAAAAASUVORK5CYII=";

/**
 * A content name containing several entities.
 */
export const CONTENT_NAME_CHALLENGE_ENTITIES = "&lt;br&gt;&amp;&quot;&#412;";
/**
 * A content name with various charsets.
 */
export const CONTENT_NAME_CHALLENGE_CHARSETS = "年Ϩ";
/**
 * A content name with RTL characters.
 */
export const CONTENT_NAME_CHALLENGE_RTL = "عامعام";
/**
 * A content name, which challenges possible Cross-Site-Scripting-Attacks.
 */
export const CONTENT_NAME_CHALLENGE_XSS = `<iframe src="javascript:alert('Boo 👻')" width="1px" height="1px">`;
/**
 * A long content name of 250 characters, which is slightly over the default
 * name length allowed in CoreMedia CMS.
 */
export const CONTENT_NAME_CHALLENGE_LENGTH =
  "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea tak";
