name: "Authorize"

on:
  workflow_call:
    secrets:
      CM_NPM_USER:
        required: true
      CM_NPM_PASSWORD:
        required: true

permissions: {}

jobs:
  env:
    uses: "./.github/workflows/env.yml"
  npm:
    name: "NPM Authorization"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - env
    env:
      NPM_URL: ${{ needs.env.outputs.npm-url }}
      GH_TOKEN: ${{ github.token }}
    steps:
      # Checkout required to invoke "gh"
      - id: checkout
        name: 'Init: Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
      - id: get-token
        name: "Get NPM Authorization Token"
        run: |
          result=$(curl -s -H "Accept: application/json" -H "Content-Type:application/json" -X PUT --data '{"name": "${{ secrets.CM_NPM_USER }}", "password": "${{ secrets.CM_NPM_PASSWORD }}"}' "${{ env.NPM_URL }}/-/user/org.couchdb.user:${{ secrets.CM_NPM_USER }}" | jq -r .token)
          # Ensure, the token is not exposed in output.
          # Unfortunately, won't work as we need to expose it as output.
          echo "::add-mask::${result}"
          # Propagate Secret as NPM_AUTH_TOKEN
          gh secret set NPM_AUTH_TOKEN --body "${result}" --app actions
