name: "Build"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  get-engines:
    uses: "./.github/workflows/get-engines.yml"
    secrets: inherit
  main:
    name: "Main"
    runs-on: ubuntu-latest
    needs:
      - get-engines
    env:
      nodeVersion: ${{ needs.get-engines.outputs.nodeVersion }}
      pnpmVersion: ${{ needs.get-engines.outputs.pnpmVersion }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: installPnpm
        name: "Install: Use PNPM ${{ env.pnpmVersion }}"
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpmVersion }}
          run_install: false
      - id: installNodeJs
        name: "Install: Use Node.js ${{ env.nodeVersion }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeVersion }}
          cache: "pnpm"
      - id: install
        name: Install
        run: |
          pnpm install --frozen-lockfile
      - id: build
        name: "Build"
        run: |
          pnpm -r build
