name: "GitHub Actions Playground"
on:
  workflow_dispatch:
jobs:
  get-version-1:
    name: "Get Version 1"
    uses: "./.github/workflows/get-version.yml"
    secrets: inherit
    with:
      release_type: pull-request
      verbose: true
