name: "GitHub Actions Playground"
on:
  workflow_dispatch:
jobs:
  get-engines:
    name: "Get Engines"
    uses: "./.github/workflows/get-engines.yml"
    secrets: inherit
  output-engines:
    runs-on: ubuntu-latest
    needs:
      - get-engines
    env:
      nodeVersion: ${{ needs.get-engines.outputs.nodeVersion }}
      pnpmVersion: ${{ needs.get-engines.outputs.pnpmVersion }}
    steps:
      - id: main
        name: "Main"
        run: |
          echo "# Detected Engines" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "* Node Version: ${{ env.nodeVersion }}" >> $GITHUB_STEP_SUMMARY
          echo "* PNPM Version: ${{ env.pnpmVersion }}" >> $GITHUB_STEP_SUMMARY
  build:
    name: "Build"
    uses: "./.github/workflows/build.yml"
    secrets: inherit
  lint:
    name: "Linter"
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      lint: true
  utest:
    name: "Unit Tests"
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      utest: true
  itest:
    name: "Integration Tests"
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      itest: true
  doc:
    name: "Generate Documentation"
    uses: "./.github/workflows/update-documentation.yml"
    secrets: inherit
