name: Pre-Release

on:
  # On push on a PR we want to trigger a normal build without publishing anything
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  # Manual trigger means we want to produce published prerelease artifacts for retesting purposes
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # do not run when if it is a manual trigger on the main branch as we have other CI for this. This one is only for feature branches
    if: (github.event_name != 'workflow_dispatch' || github.ref != 'refs/heads/main') && !github.event.pull_request.draft
    env:
      NPM_CONFIG_@coremedia:registry: 'https://npm.coremedia.io'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Allocate PR Number for manual trigger
        id: read-prnumber
        if: github.event_name == 'workflow_dispatch'
        run: |
          prnumber=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{github.repository}}/pulls?head=${{github.repository_owner}}:${{github.ref}} | jq -r '.[] | .number' )
          echo "Allocated Pull Request number ${prnumber}"
          echo "::set-output name=prnumber::${prnumber}"
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.1.5
      - name: Install additional tools
        run: |
          pnpm install -g semver
      - name: Setup npm.coremedia.io
        run: |
          NPM_AUTH_TOKEN=$(curl -s -H "Accept: application/json" -H "Content-Type:application/json" -X PUT --data '{"name": "${{ secrets.CM_NPM_USER }}", "password": "${{ secrets.CM_NPM_READ_ONLY_PASSWORD }}"}' https://npm.coremedia.io/-/user/org.couchdb.user:${{ secrets.CM_NPM_USER }} | jq -r .token)
          echo "::add-mask::$NPM_AUTH_TOKEN"
          pnpm config set //npm.coremedia.io/:_authToken=$NPM_AUTH_TOKEN
          pnpm config set @coremedia:registry=https://npm.coremedia.io
          pnpm config set @jangaroo:registry=https://npm.coremedia.io
      - name: Setup Git
        run: |
          git config --global user.name 'coremedia-ci'
          git config --global user.email 'coremedia-ci@coremedia.com'
      - name: Install
        run: pnpm install
      - name: Set prerelease version (if triggered manually)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status
            echo "error:: There are unexpected changes in git!";
            exit 1
          fi
          actual_version=$(cat .release-version)
          prnumber=${{ steps.read-prnumber.outputs.prnumber }}
          next_version=$(semver --increment prerelease --preid pr${prnumber}-${{ github.run_number }} ${actual_version})
          pnpm run setversion ${next_version} --filter=coremedia/* --dependencyVersion=${next_version}
          pnpm install --no-frozen-lockfile
          git commit -am "Set PR Version: ${next_version}"
          echo "Chosen Pre-Release Version: ${next_version}"
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm jest
      - name: TypeDoc
        run: pnpm doc
      - name: Publish prerelease
        if: github.event_name == 'workflow_dispatch'
        run: |
          pnpm install --production
          echo '//npm.coremedia.io/:_authToken=${NPM_AUTH_TOKEN}' > .npmrc
          pnpm publishall --registry=https://npm.coremedia.io --no-git-checks --tag pullrequest
