name: Pre-Release

on:
  # On push on a PR we want to trigger a normal build without publishing anything
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  # Manual trigger means we want to produce published prerelease artifacts for retesting purposes
  workflow_dispatch:

env:
  NODE_VERSION: 18
  # https://github.com/actions/runner-images/issues/70
  NODE_OPTIONS: "--max_old_space_size=4096"
  PNPM_VERSION: ^8.1
  NPM_CONFIG_@coremedia:registry: 'https://npm.coremedia.io'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 13
    # do not run when if it is a manual trigger on the main branch as we have other CI for this. This one is only for feature branches
    if: (github.event_name != 'workflow_dispatch' || github.ref != 'refs/heads/main') && !github.event.pull_request.draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Allocate PR Number for manual trigger
        id: read-prnumber
        if: github.event_name == 'workflow_dispatch'
        run: |
          prnumber=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{github.repository}}/pulls?head=${{github.repository_owner}}:${{github.ref}} | jq -r '.[] | .number' )
          echo "Allocated Pull Request number ${prnumber}"
          echo "::set-output name=prnumber::${prnumber}"
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Push commits
        run: git push origin ci/fix-github-actions:ci/fix-github-actions-test
